### ISSUE TITLE
Relation of resource to the mixed type

### ISSUE THREAD

**Issue by kocsismate** [Danack/MixedRFC#4]
Currently, the RFC suggests that the `mixed` type is equivalent to the `array|bool|callable|int|float|null|object|resource|string` union type.

This is not exactly correct, since `resource` is not a valid type in PHP.  Additionally, it also implies that the `mixed` type can't be expressed via union types. That's why the RFC should clarify this.

**Comment by Danack** [comment]
Ugh, yes. I had blanked out the resource type....

**Comment by Danack** [comment]
This was fixed through PR.
